version: '3.7'

# Networks
networks:
  # Internal network
  internal:
    driver: bridge

# Volumes
volumes:
  # MySQL volume
  mysql-dev_data:
    driver: local

services:

  # api
  apache-dev:
    image: webdevops/php-apache-dev:8.1
    container_name: apache-dev
    networks:
      - internal
    working_dir: /var/www/app
    volumes:
      - .:/var/www/app
    depends_on:
      - mysql-dev
    environment:
      - WEB_DOCUMENT_ROOT=/var/www/app
      - PHP_DEBUGGER="xdebug"
      - XDEBUG_REMOTE_AUTOSTART=On
      - XDEBUG_REMOTE_CONNECT_BACK=Off
      - XDEBUG_REMOTE_HOST=host.docker.internal
      - XDEBUG_REMOTE_PORT=9090
      - XDEBUG_PROFILER_ENABLE=Off
      - PHP_DATE_TIMEZONE=UTC
      - PHP_DISPLAY_ERRORS=0
      - WEB_DOCUMENT_INDEX=index.php
      - PHP_MEMORY_LIMIT=2048M
      - PHP_MAX_EXECUTION_TIME=86400
      - PHP_POST_MAX_SIZE=500M
      - PHP_UPLOAD_MAX_FILESIZE=500M
    ports:
      - 30202:80

  # MySQL
  mysql-dev:
    image: mysql:5.7
    container_name: mysql-dev
    networks:
      - internal
    working_dir: /var/www/app
    volumes:
      - mysql-dev_data:/var/lib/mysql
      - .:/var/www/app
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=banco_de_talentos
      - MYSQL_USER=talent
      - MYSQL_PASSWORD=talent
    ports:
      - 3000:3306